# Generated by Django 5.1.5 on 2025-03-24 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CognitiveTestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('options', models.JSONField()),
                ('correct_answer', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='healthdahboard',
            name='user',
        ),
        migrations.CreateModel(
            name='HealthDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brain_health_score', models.FloatField()),
                ('risk_areas', models.JSONField()),
                ('prevention_strategies', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.DeleteModel(
            name='CognitiveTest',
        ),
        migrations.DeleteModel(
            name='HealthDahboard',
        ),
    ]
