# Generated by Django 5.1.5 on 2025-03-29 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cognitivetestquestion_remove_healthdahboard_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifestyleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sleep_hours', models.FloatField()),
                ('water_intake', models.IntegerField()),
                ('mood', models.CharField(max_length=20)),
                ('exercise_type', models.CharField(max_length=50)),
                ('exercise_duration', models.IntegerField()),
                ('exercise_intensity', models.CharField(max_length=20)),
                ('fruits', models.IntegerField()),
                ('vegetables', models.IntegerField()),
                ('processed_foods', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
