# Generated by Django 5.1.5 on 2025-03-31 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_lifestyleentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifestyleData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sleep', models.IntegerField()),
                ('water', models.IntegerField()),
                ('steps', models.IntegerField()),
                ('exercise', models.IntegerField()),
                ('mood', models.IntegerField()),
                ('nutrition', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
