# Generated by Django 5.1.5 on 2025-03-31 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_lifestyledata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lifestyledata',
            options={},
        ),
        migrations.RenameField(
            model_name='lifestyledata',
            old_name='nutrition',
            new_name='record',
        ),
        migrations.RemoveField(
            model_name='lifestyledata',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='lifestyledata',
            name='mood',
        ),
        migrations.RemoveField(
            model_name='lifestyledata',
            name='sleep',
        ),
        migrations.RemoveField(
            model_name='lifestyledata',
            name='steps',
        ),
        migrations.RemoveField(
            model_name='lifestyledata',
            name='user',
        ),
        migrations.RemoveField(
            model_name='lifestyledata',
            name='water',
        ),
        migrations.AlterField(
            model_name='lifestyledata',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
