# Generated by Django 5.1.5 on 2025-04-01 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_patient_birth_date'),
    ]

    operations = [
    ]
