# Generated by Django 5.1.5 on 2025-04-01 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_birth_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrainHealthAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('cognitive_score', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CognitiveTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('total_questions', models.IntegerField()),
                ('correct_answers', models.IntegerField()),
                ('details', models.JSONField()),
                ('date_taken', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('cognitive', 'Cognitive'), ('physical', 'Physical Activity'), ('nutrition', 'Nutrition'), ('sleep', 'Sleep'), ('stress', 'Stress Management'), ('social', 'Social Engagement')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='caregiveraccesslog',
            name='caregiver',
        ),
        migrations.RemoveField(
            model_name='caregiveraccesslog',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='healthdashboard',
            name='user',
        ),
        migrations.RemoveField(
            model_name='lifestyleentry',
            name='user',
        ),
        migrations.DeleteModel(
            name='PatientData',
        ),
        migrations.RemoveField(
            model_name='riskfactor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='caregiver',
            name='license_number',
        ),
        migrations.RemoveField(
            model_name='lifestyledata',
            name='date',
        ),
        migrations.RemoveField(
            model_name='lifestyledata',
            name='record',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='conditions',
        ),
        migrations.AddField(
            model_name='caregiver',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='caregiver',
            name='qualifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cognitivetestquestion',
            name='difficulty',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cognitivetestquestion',
            name='question_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lifestyledata',
            name='alcohol',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lifestyledata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='lifestyledata',
            name='good_sleep',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lifestyledata',
            name='healthy_diet',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lifestyledata',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lifestyledata',
            name='physical_activity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lifestyledata',
            name='smoking',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lifestyledata',
            name='social_engagement',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lifestyledata',
            name='stress',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='lifestyledata',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='caregiver',
            name='patients',
            field=models.ManyToManyField(blank=True, related_name='caregivers', to='api.patient'),
        ),
        migrations.AlterField(
            model_name='caregiver',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='caregiver_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cognitivetestquestion',
            name='correct_answer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cognitivetestquestion',
            name='options',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='cognitivetestquestion',
            name='question',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='pendingverification',
            unique_together={('caregiver', 'patient')},
        ),
        migrations.AddField(
            model_name='brainhealthassessment',
            name='lifestyle_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.lifestyledata'),
        ),
        migrations.AddField(
            model_name='brainhealthassessment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='api.patient'),
        ),
        migrations.AddField(
            model_name='cognitivetestresult',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cognitive_tests', to='api.patient'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='api.patient'),
        ),
        migrations.DeleteModel(
            name='CaregiverAccessLog',
        ),
        migrations.DeleteModel(
            name='HealthDashboard',
        ),
        migrations.DeleteModel(
            name='LifestyleEntry',
        ),
        migrations.DeleteModel(
            name='RiskFactor',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
