# Generated by Django 5.1.5 on 2025-04-02 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_brainhealthassessment_cognitivetestresult_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lifestyledata',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='lifestyledata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifestyle_entries', to=settings.AUTH_USER_MODEL),
        ),
    ]
