# Generated by Django 5.1.5 on 2025-04-05 05:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_lifestyledata_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifestyledata',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
